### ISSUE TITLE
74HC or 74HCT

### ISSUE THREAD

**Issue by EtchedPixels** [skiselev/easy_z80#1]
The BOM gives 74HCT part numbers against 74HC Mouser links ?

**Comment by skiselev** [comment]
It doesn't really matter, either 74HC or 74HCT should work with CMOS Z84C00 CPU. If using NMOS Z80 CPU, I'd recommend using 74HCT.
The reason I've used 74HC in the Mouser BOM is that 74HCT670's are ridiculously expensive, and 74HC670 quite a bit cheaper.

**Comment by EtchedPixels** [comment]
Ok thanks..

**Comment by skiselev** [comment]
For the sake of consistency, I'll update the BOM. And for the next revision of the PCB, I'll also update the silkscreen.

**Comment by skiselev** [comment]
The logic ICs are changed to 74HC series in version 1.1.
Thanks for the feedback!
