### ISSUE TITLE
Can 74LSxxx be used as a replacement for 74HCTxxx/74HCxxx

### ISSUE THREAD

**Issue by ericzhang-debug** [skiselev/easy_z80#5]
hello, Can 74LSxxx be used as a replacement for 74HCTxxx/74HCxxx in this project? Can it work normally?

**Comment by skiselev** [comment]
I think it will work.
A few notes:
- Don't mix 74HC with 74LS
- It's ok to mix 74HCT with 74LS
- Power consumption might go up a bit
